# Generated by Django 4.2.16 on 2024-09-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='Score',
            field=models.IntegerField(default=0),
        ),
    ]
