# Generated by Django 4.2.16 on 2024-09-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_studentdetails_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='ProfileImage',
            field=models.ImageField(blank=True, null=True, upload_to='student_images/'),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='Register',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='stdId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
