# Generated by Django 4.2.16 on 2024-09-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_studentdetails_profileimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='Register',
            field=models.IntegerField(default=0),
        ),
    ]
