# Generated by Django 4.2.16 on 2024-09-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_studentdetails_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetails',
            name='Score',
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='Email',
            field=models.EmailField(max_length=100),
        ),
    ]
